### ISSUE TITLE
Roadmap v0.1

### ISSUE THREAD

**Issue by nogic1008** [ddradar/nuxt-swa#29]
## Enhancements
- [x] Provide `nitro.azure.config` type (#30)
- [x] Auto detect identity provider from `nitro.azure.config` (#31)
- [x] Warn `nitro.azure.config` is undefined (#32)
- ~~Warn if [Custom Providers](https://learn.microsoft.com/azure/static-web-apps/authentication-custom)  are set in `authProviders` and the settings are not in `nitro.azure.config`~~
  - add deprecated tag on `authProviders` next release
## Testing
- [x] unit test for type generation (#30)
## Development
- [x] Setup devcontainer (#33)
- [x] Add `nuxt` dependencies group (#36)
